### ISSUE TITLE
Spigot Server Crash - Could Be Linked To ChopChop

### ISSUE THREAD

**Issue by anselhelm** [XSoussou/ChopChop#7]
Hi,

Sorry to trouble you. I had a recent server crash, for which I've pasted the dump here:
[https://pastebin.com/ke2bS8JF](https://pastebin.com/ke2bS8JF)

It seems to involve Wildstacker and ChopChop. I've notified the [Wildstacker](https://github.com/OmerBenGera/WildStacker) developer separately, but wanted to also let you know about this, in case there's a bug in ChopChop or a compatibility issue between the plugins.

Thanks for looking into this :)

**Comment by XSoussou** [comment]
Hi and thank you for letting me know about this !

Unfortunately, I don't think I can do anything to solve your problem, since all ChopChop is doing when breaking a tree is destroying its individual blocks in the natural "Bukkit" way.

So I don't know what made the crash happen, but I hope you'll find out x)
(also sorry for late response :ccc )

**Comment by anselhelm** [comment]
No worries whatsoever. I figure it was probably an issue caused by Wildstacker, which I've now stopped using in favour of a different plugin. Thanks again for taking the time to reply and hope this message finds you well :)
